### ISSUE TITLE
docker-entrypoint.sh没加权限，通过hub docker打出来的就没权限了。

### ISSUE THREAD

**Issue by bestbugwriter** [enmotech/enmotech-docker-opengauss#1]
https://github.com/enmotech/enmotech-docker-opengauss/blob/2037dd2bf9b7ba2b0ef75b4ba6f630ce58b275a8/1.0.0/dockerfile#L42

**Comment by travelliu** [comment]
已解决. 其实现在这个没办法通过hub.docker 构建。gaussdb的安装包现在没有从网络上获取,构建出来也应该是错误的
