### ISSUE TITLE
制作镜像过程中报错（xshell中红色字体在本页已加粗显示）

### ISSUE THREAD

**Issue by estrellaFZTH** [enmotech/enmotech-docker-opengauss#11]
[root@s1 enmotech-docker-opengauss]# sh buildDockerImage.sh -v 1.0.1 -i
Checking Docker version.
Ignored MD5 checksum.
==========================
DOCKER info:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 128
  Running: 53
  Paused: 0
  Stopped: 75
 Images: 118
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.11.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.25GiB
 Name: s1
 ID: 3B6A:UF4P:MMPV:QHTC:5RRL:JCEL:SJQH:NU2X:RFUP:442O:4WN4:XXBM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ructrx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://euo9a7t5.mirror.aliyuncs.com/
  https://hub-mirror.c.163.com/
  https://mirror.baidubce.com/
 Live Restore Enabled: false

==========================
Building image 'opengauss:1.0.1' ...
Sending build context to Docker daemon  217.4MB
Step 1/14 : FROM centos:7.6.1810
 ---> f1cb7c7d58b7
Step 2/14 : COPY openGauss-1.0.1-CentOS-64bit.tar.bz2 .
 ---> 89226f34b13b
Step 3/14 : COPY gosu-amd64 /usr/local/bin/gosu
 ---> b78e7eea496b
Step 4/14 : ENV LANG en_US.utf8
 ---> Running in c2763fd4f0b6
Removing intermediate container c2763fd4f0b6
 ---> b2c298a792bf
Step 5/14 : RUN set -eux;     yum install -y bzip2 bzip2-devel curl libaio&&     groupadd -g 70 omm;      useradd -u 70 -g omm -d /home/omm omm;      mkdir -p /var/lib/opengauss &&     mkdir -p /usr/local/opengauss &&     mkdir -p /var/run/opengauss  &&     mkdir /docker-entrypoint-initdb.d &&     tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &&     chown -R omm:omm /var/run/opengauss && chown -R omm:omm /usr/local/opengauss && chown -R omm:omm /var/lib/opengauss &&  chown -R omm:omm /docker-entrypoint-initdb.d &&     chmod 2777 /var/run/opengauss &&     rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 && yum clean all
 ---> Running in 61b97513e42e
**+ yum install -y bzip2 bzip2-devel curl libaio**
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
**+ useradd -u 70 -g omm -d /home/omm omm
useradd: group 'omm' does not exist**
Removing intermediate container 61b97513e42e
The command '/bin/sh -c set -eux;     yum install -y bzip2 bzip2-devel curl libaio&&     groupadd -g 70 omm;      useradd -u 70 -g omm -d /home/omm omm;      mkdir -p /var/lib/opengauss &&     mkdir -p /usr/local/opengauss &&     mkdir -p /var/run/opengauss  &&     mkdir /docker-entrypoint-initdb.d &&     tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &&     chown -R omm:omm /var/run/opengauss && chown -R omm:omm /usr/local/opengauss && chown -R omm:omm /var/lib/opengauss &&  chown -R omm:omm /docker-entrypoint-initdb.d &&     chmod 2777 /var/run/opengauss &&     rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 && yum clean all' returned a non-zero code: 6

ERROR: openGauss Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.

**Comment by lee1057** [comment]
基础镜像yum源的问题，先把基础镜像下载到本地，然后在跑一下试试。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："estrellaFZTH ***@***.***&gt;;
发送时间：2021年7月22日(星期四) 晚上9:46
收件人："enmotech/enmotech-docker-opengauss" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[enmotech/enmotech-docker-opengauss] 制作镜像过程中报错（xshell中红色字体在本页已加粗显示） (#11)
-----------------------------------

 

 
***@***.*** enmotech-docker-opengauss]# sh buildDockerImage.sh -v 1.0.1 -i
 Checking Docker version.
 Ignored MD5 checksum.
 
DOCKER info:
 Client:
 Context:    default
 Debug Mode: false
 Plugins:
 app: Docker App (Docker Inc., v0.9.1-beta3)
 buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
 
Server:
 Containers: 128
 Running: 53
 Paused: 0
 Stopped: 75
 Images: 118
 Server Version: 19.03.11
 Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
 seccomp
 Profile: default
 Kernel Version: 3.10.0-1160.11.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.25GiB
 Name: s1
 ID: 3B6A:UF4P:MMPV:QHTC:5RRL:JCEL:SJQH:NU2X:RFUP:442O:4WN4:XXBM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ructrx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
 127.0.0.0/8
 Registry Mirrors:
 https://euo9a7t5.mirror.aliyuncs.com/
 https://hub-mirror.c.163.com/
 https://mirror.baidubce.com/
 Live Restore Enabled: false
 
==========================
 Building image 'opengauss:1.0.1' ...
 Sending build context to Docker daemon  217.4MB
 Step 1/14 : FROM centos:7.6.1810
 ---&gt; f1cb7c7d58b7
 Step 2/14 : COPY openGauss-1.0.1-CentOS-64bit.tar.bz2 .
 ---&gt; 89226f34b13b
 Step 3/14 : COPY gosu-amd64 /usr/local/bin/gosu
 ---&gt; b78e7eea496b
 Step 4/14 : ENV LANG en_US.utf8
 ---&gt; Running in c2763fd4f0b6
 Removing intermediate container c2763fd4f0b6
 ---&gt; b2c298a792bf
 Step 5/14 : RUN set -eux;     yum install -y bzip2 bzip2-devel curl libaio&amp;&amp;     groupadd -g 70 omm;      useradd -u 70 -g omm -d /home/omm omm;      mkdir -p /var/lib/opengauss &amp;&amp;     mkdir -p /usr/local/opengauss &amp;&amp;     mkdir -p /var/run/opengauss  &amp;&amp;     mkdir /docker-entrypoint-initdb.d &amp;&amp;     tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &amp;&amp;     chown -R omm:omm /var/run/opengauss &amp;&amp; chown -R omm:omm /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/lib/opengauss &amp;&amp;  chown -R omm:omm /docker-entrypoint-initdb.d &amp;&amp;     chmod 2777 /var/run/opengauss &amp;&amp;     rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 &amp;&amp; yum clean all
 ---&gt; Running in 61b97513e42e
 + yum install -y bzip2 bzip2-devel curl libaio
 Loaded plugins: fastestmirror, ovl
 Determining fastest mirrors
 
One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
  1. Contact the upstream for the repository and get them to fix the problem.  2. Reconfigure the baseurl/etc. for the repository, to point to a working     upstream. This is most often useful if you are using a newer     distribution release than is supported by the repository (and the     packages for the previous distribution release still work).  3. Run the command with the repository temporarily disabled         yum --disablerepo=<repoid&gt; ...  4. Disable the repository permanently, so yum won't use it by default. Yum     will then just ignore the repository until you permanently enable it     again or use --enablerepo for temporary usage:         yum-config-manager --disable <repoid&gt;     or         subscription-manager repos --disable=<repoid&gt;  5. Configure the failing repository to be skipped, if it is unavailable.     Note that yum will try to contact the repo. when it runs most commands,     so will have to try and fail each time (and thus. yum will be be much     slower). If it is a very temporary problem though, this is often a nice     compromise:         yum-config-manager --save --setopt=<repoid&gt;.skip_if_unavailable=true  
Cannot find a valid baseurl for repo: base/7/x86_64
 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&amp;arch=x86_64&amp;repo=os&amp;infra=container error was
 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
 + useradd -u 70 -g omm -d /home/omm omm
 useradd: group 'omm' does not exist
 Removing intermediate container 61b97513e42e
 The command '/bin/sh -c set -eux;     yum install -y bzip2 bzip2-devel curl libaio&amp;&amp;     groupadd -g 70 omm;      useradd -u 70 -g omm -d /home/omm omm;      mkdir -p /var/lib/opengauss &amp;&amp;     mkdir -p /usr/local/opengauss &amp;&amp;     mkdir -p /var/run/opengauss  &amp;&amp;     mkdir /docker-entrypoint-initdb.d &amp;&amp;     tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &amp;&amp;     chown -R omm:omm /var/run/opengauss &amp;&amp; chown -R omm:omm /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/lib/opengauss &amp;&amp;  chown -R omm:omm /docker-entrypoint-initdb.d &amp;&amp;     chmod 2777 /var/run/opengauss &amp;&amp;     rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 &amp;&amp; yum clean all' returned a non-zero code: 6
 
ERROR: openGauss Database Docker Image was NOT successfully created.
 ERROR: Check the output and correct any reported problems with the docker build operation.

**Comment by estrellaFZTH** [comment]
> 
> 基础镜像yum源的问题，先把基础镜像下载到本地，然后在跑一下试试。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："estrellaFZTH ***@***.***&gt;; 发送时间：2021年7月22日(星期四) 晚上9:46 收件人："enmotech/enmotech-docker-opengauss" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[enmotech/enmotech-docker-opengauss] 制作镜像过程中报错（xshell中红色字体在本页已加粗显示） (#11) ----------------------------------- ***@***.*** enmotech-docker-opengauss]# sh buildDockerImage.sh -v 1.0.1 -i Checking Docker version. Ignored MD5 checksum. DOCKER info: Client: Context: default Debug Mode: false Plugins: app: Docker App (Docker Inc., v0.9.1-beta3) buildx: Build with BuildKit (Docker Inc., v0.5.1-docker) Server: Containers: 128 Running: 53 Paused: 0 Stopped: 75 Images: 118 Server Version: 19.03.11 Storage Driver: overlay2 Backing Filesystem: extfs Supports d_type: true Native Overlay Diff: true Logging Driver: json-file Cgroup Driver: systemd Plugins: Volume: local Network: bridge host ipvlan macvlan null overlay Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog Swarm: inactive Runtimes: runc Default Runtime: runc Init Binary: docker-init containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd init version: fec3683 Security Options: seccomp Profile: default Kernel Version: 3.10.0-1160.11.1.el7.x86_64 Operating System: CentOS Linux 7 (Core) OSType: linux Architecture: x86_64 CPUs: 4 Total Memory: 15.25GiB Name: s1 ID: 3B6A:UF4P:MMPV:QHTC:5RRL:JCEL:SJQH:NU2X:RFUP:442O:4WN4:XXBM Docker Root Dir: /var/lib/docker Debug Mode: false Username: ructrx Registry: https://index.docker.io/v1/ Labels: Experimental: false Insecure Registries: 127.0.0.0/8 Registry Mirrors: https://euo9a7t5.mirror.aliyuncs.com/ https://hub-mirror.c.163.com/ https://mirror.baidubce.com/ Live Restore Enabled: false ========================== Building image 'opengauss:1.0.1' ... Sending build context to Docker daemon 217.4MB Step 1/14 : FROM centos:7.6.1810 ---&gt; f1cb7c7d58b7 Step 2/14 : COPY openGauss-1.0.1-CentOS-64bit.tar.bz2 . ---&gt; 89226f34b13b Step 3/14 : COPY gosu-amd64 /usr/local/bin/gosu ---&gt; b78e7eea496b Step 4/14 : ENV LANG en_US.utf8 ---&gt; Running in c2763fd4f0b6 Removing intermediate container c2763fd4f0b6 ---&gt; b2c298a792bf Step 5/14 : RUN set -eux; yum install -y bzip2 bzip2-devel curl libaio&amp;&amp; groupadd -g 70 omm; useradd -u 70 -g omm -d /home/omm omm; mkdir -p /var/lib/opengauss &amp;&amp; mkdir -p /usr/local/opengauss &amp;&amp; mkdir -p /var/run/opengauss &amp;&amp; mkdir /docker-entrypoint-initdb.d &amp;&amp; tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/run/opengauss &amp;&amp; chown -R omm:omm /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/lib/opengauss &amp;&amp; chown -R omm:omm /docker-entrypoint-initdb.d &amp;&amp; chmod 2777 /var/run/opengauss &amp;&amp; rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 &amp;&amp; yum clean all ---&gt; Running in 61b97513e42e + yum install -y bzip2 bzip2-devel curl libaio Loaded plugins: fastestmirror, ovl Determining fastest mirrors One of the configured repositories failed (Unknown), and yum doesn't have enough cached data to continue. At this point the only safe thing yum can do is fail. There are a few ways to work "fix" this: 1. Contact the upstream for the repository and get them to fix the problem. 2. Reconfigure the baseurl/etc. for the repository, to point to a working upstream. This is most often useful if you are using a newer distribution release than is supported by the repository (and the packages for the previous distribution release still work). 3. Run the command with the repository temporarily disabled yum --disablerepo=<repoid&gt; ... 4. Disable the repository permanently, so yum won't use it by default. Yum will then just ignore the repository until you permanently enable it again or use --enablerepo for temporary usage: yum-config-manager --disable <repoid&gt; or subscription-manager repos --disable=<repoid&gt; 5. Configure the failing repository to be skipped, if it is unavailable. Note that yum will try to contact the repo. when it runs most commands, so will have to try and fail each time (and thus. yum will be be much slower). If it is a very temporary problem though, this is often a nice compromise: yum-config-manager --save --setopt=<repoid&gt;.skip_if_unavailable=true Cannot find a valid baseurl for repo: base/7/x86_64 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&amp;arch=x86_64&amp;repo=os&amp;infra=container error was 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error" + useradd -u 70 -g omm -d /home/omm omm useradd: group 'omm' does not exist Removing intermediate container 61b97513e42e The command '/bin/sh -c set -eux; yum install -y bzip2 bzip2-devel curl libaio&amp;&amp; groupadd -g 70 omm; useradd -u 70 -g omm -d /home/omm omm; mkdir -p /var/lib/opengauss &amp;&amp; mkdir -p /usr/local/opengauss &amp;&amp; mkdir -p /var/run/opengauss &amp;&amp; mkdir /docker-entrypoint-initdb.d &amp;&amp; tar -jxvf openGauss-1.0.1-CentOS-64bit.tar.bz2 -C /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/run/opengauss &amp;&amp; chown -R omm:omm /usr/local/opengauss &amp;&amp; chown -R omm:omm /var/lib/opengauss &amp;&amp; chown -R omm:omm /docker-entrypoint-initdb.d &amp;&amp; chmod 2777 /var/run/opengauss &amp;&amp; rm -rf openGauss-1.0.1-CentOS-64bit.tar.bz2 &amp;&amp; yum clean all' returned a non-zero code: 6 ERROR: openGauss Database Docker Image was NOT successfully created. ERROR: Check the output and correct any reported problems with the docker build operation. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问是把报错的那行 yum 后面的源的基础镜像下载到本地，再试着跑一下吗？
师兄说，前一段时间还没有问题，突然就出问题了。

**Comment by estrellaFZTH** [comment]
问题已解决，重启了下docker
