### ISSUE TITLE
如何设置鉴权方式呢

### ISSUE THREAD

**Issue by jifengnan** [enmotech/enmotech-docker-opengauss#12]
现在鉴权方式是MD5，我看可以通过 GS_HOST_AUTH_METHOD 设置鉴权方式，但好像不起作用

**Comment by kamusis** [comment]
![image](https://user-images.githubusercontent.com/1849506/129831926-cb32220a-09b4-4ea7-9700-8258bc03ee4f.png)
目前只是正式支持以上4个参数的设定，其它的还未正式支持。下一个版本会提供更多参数的支持，包括HOST_AUTH_METHOD。

**Comment by kamusis** [comment]
如果需要修改容器数据库的密码认证方式，也可以在容器数据库创建完毕以后，手工修改pg_hba.conf文件，跟普通数据库一样。这个修改也是持久化的，docker stop之后重新启动也仍然能够保持。

**Comment by lee1057** [comment]
这个参数是可以设置的，是不是使用方法的问题，要指定多个-e。
docker run --name mogdb_test3  --privileged=true -d -e GS_PASSWORD=Enmo@123 -e GS_HOST_AUTH_METHOD=sha256  opengauss:2.0.1
