### ISSUE TITLE
更改为sha256后不生效

### ISSUE THREAD

**Issue by jifengnan** [enmotech/enmotech-docker-opengauss#13]
我到 docker 容器的 /var/lib/opengauss/data 里
把 pg_hba.conf 改成了 sha256: host all all 0.0.0.0/0 sha256
把 postgresql.conf 中的 password_encryption_type 改成了 2: password_encryption_type = 2
但是启动后，还是用 MD5 认证。

**Comment by kamusis** [comment]
请问您是怎么启动的？
docker run是启动新的容器。
需要用docker start启动之前你修改过的容器。
另外， 您是怎么验证是用sha256认证还是MD5认证的？

--
Kamus ***@***.***>
在 2021年8月22日 +0900 13:28，jifengnan ***@***.***>，写道：

**Comment by jifengnan** [comment]
启动是 docker start
验证是通过数据库驱动，打断点，检测服务器端发回的标志位。

**Comment by kamusis** [comment]
能把您整个操作过程发给我们吗？我们尝试复现一下。特别是最后断点判断仍然不是SHA256验证的部分。

--
Kamus ***@***.***>
在 2021年8月22日 +0900 20:58，jifengnan ***@***.***>，写道：

**Comment by jifengnan** [comment]
JAVA 用的比较多，这里提供个JAVA的驱动： https://gitee.com/opengauss/openGauss-connector-jdbc/tree/master/pgjdbc
随便跑一个单元测试，比如 org.postgresql.test.jdbc2.PreparedStatementTest#getNumberOfServerPreparedStatements
打断点在 org.postgresql.core.v3.ConnectionFactoryImpl#doAuthentication 的 539 行，最终会走入 MD5 认证

**Comment by saxisuer** [comment]
可以在数据库中执行 SHOW password_encryption_type; 看一下参数修改是否生效了么?

**Comment by saxisuer** [comment]
@jifengnan 我这边复现了你的场景,如果你更改了加密方式并且加密方式生效了 需要创建新的用户 新的用户通过SHA256 加密 登陆认证也会走SHA256的逻辑.

**Comment by kamusis** [comment]
> 我到 docker 容器的 /var/lib/opengauss/data 里
> 把 pg_hba.conf 改成了 sha256: host all all 0.0.0.0/0 sha256
> 把 postgresql.conf 中的 password_encryption_type 改成了 2: password_encryption_type = 2
> 但是启动后，还是用 MD5 认证。

请在postgresql.conf中检查一下是否存在了多个password_encryption_type，导致配置被覆盖

**Comment by jifengnan** [comment]
@saxisuer 感谢，我试试
