### ISSUE TITLE
docker 3.0.0 内找不到gs_om命令 且gs_guc 显示找不到对应配置文件

### ISSUE THREAD

**Issue by 1173710214** [enmotech/enmotech-docker-opengauss#14]
登录omm账号后 找不到 gs_om命令 gs_guc也没办法执行.
不知道是不是因为使用lite的原因.

**Comment by lee1057** [comment]
容器版本没有gs_om和gs_guc。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："oking9 ***@***.***&gt;;
发送时间：2022年5月3日(星期二) 上午8:42
收件人："enmotech/enmotech-docker-opengauss" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[enmotech/enmotech-docker-opengauss] docker 3.0.0 内找不到gs_om命令 且gs_guc 显示找不到对应配置文件 (Issue #14)
-----------------------------------

 

 
登录omm账号后 找不到 gs_om命令 gs_guc也没办法执行.
 不知道是不是因为使用lite的原因.

**Comment by 1173710214** [comment]
噢噢噢~ 感谢回复 要是方便请问能加个联系方式详细问一下吗?

**Comment by 1173710214** [comment]
容器内, root和omm 都无法使用gsql. 请问这个是为什么呢? 难道只能从外部连接? 那外部有办法在不安装完整opengauss的情况下安装gsql吗?

**Comment by lee1057** [comment]
麻烦发一下操作步骤，和截图。

**Comment by kamusis** [comment]
容器内gsql是可以正常运行的。

/root~ # docker ps | grep opengauss
dd2e967ac6e9 enmotech/opengauss:3.0.0 "entrypoint.sh gauss…" 4 weeks ago Up 7 days 0.0.0.0:15432->5432/tcp og30

/root~ # docker exec -it og30 bash
***@***.***:/# su - omm
***@***.***:~$ gsql -d postgres
gsql ((openGauss 3.0.0 build 02c14696) compiled at 2022-04-01 18:28:23 commit 0 last mr release)
Non-SSL connection (SSL connection is recommended when requiring high-security)
Type "help" for help.

openGauss=# select version();
 version
--------------------------------------------------------------------------------------------
 (openGauss 3.0.0 build 02c14696) compiled at 2022-04-01 18:28:23 commit 0 last mr release
(1 row)

openGauss=#

--
Kamus ***@***.***>
在 2022年5月3日 +0900 17:14，oking9 ***@***.***>，写道：

**Comment by 1173710214** [comment]
谢谢确实3.0.0是可以正常使用gsql的, 但是我当时拉取所有仓库时自动下的是3.0(仓库内所有版本信息如下). 然后发现如果用3.0会出现下面的情况.

\----------------------------------------------------------------------------------------------
(base) oking@oking:$ sudo docker images                                       
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE              
enmotech/opengauss   2.1.0     b4dd24d09223   7 months ago    383MB             
enmotech/opengauss   latest    b4dd24d09223   7 months ago    383MB             
enmotech/opengauss   2.0.1     c3860afd8014   8 months ago    404MB             
enmotech/opengauss   2.0.0     39eb4c00127d   13 months ago   404MB             
enmotech/opengauss   1.1.0     a6241b159a1d   16 months ago   651MB             
enmotech/opengauss   1.0.1     80711c4eb80a   19 months ago   485MB             
enmotech/opengauss   1.0.0     71801e231389   22 months ago   467MB             
enmotech/opengauss   3.0       4d3304e129df   22 months ago   1.93GB

(base) oking@oking:$ sudo docker run --name opengauss --privileged=true -d -e GS_PASSWORD=Secretpassword@123     -v /enmotech/opengauss_test:/var/lib/opengauss  -u root -p 15433:5432 enmotech/opengauss:3.0                                  819b2fa3475277848b34fd4730fb4d73992242b5b38026e830ad2ee326d3b3c8                
(base) oking@oking:$ sudo docker exec -it opengauss bash                       
[root@819b2fa34752 /]# su - omm                                                 
Last login: Tue Jun 23 07:00:37 UTC 2020 on pts/0                               
[omm@819b2fa34752 ~]$ gsql -d postgres                                          
-bash: gsql: command not found                                                  
[omm@819b2fa34752 ~]$

**Comment by 1173710214** [comment]
但是gs_guc似乎没有办法正常执行(check or reload).

omm@a0b3bbdf3c4e:/$ gs_guc check -D /gaussdb/data/dbnode -c "max_connections" -N ALL                                                                            
The gs_guc run with the following arguments: [gs_guc -D /gaussdb/data/dbnode -c max_connections -N ALL check ].                                                 realpath(/usr/local/opengauss/bin/cluster_static_config) failed : No such file or directory!                                                                    
ERROR: Failed to get cluster information from static configuration file.
omm@a0b3bbdf3c4e:/$ gs_guc reload -N all -I all -c "authentication_timeout = 59s"                                                                               
The gs_guc run with the following arguments: [gs_guc -N all -I all -c authentication_timeout = 59s reload ].                                                    realpath(/usr/local/opengauss/bin/cluster_static_config) failed : No such file or directory!                                                                    
ERROR: Failed to get cluster information from static configuration file. 

然后也找不到docker内的gs_om.

root@a0b3bbdf3c4e:/# find . -type f | grep gs_om                                
root@a0b3bbdf3c4e:/# 
omm@a0b3bbdf3c4e:/$ gs_om                                                       
bash: gs_om: command not found

**Comment by lee1057** [comment]
gs_guc 和 gs_om命令容器里边是没有的，想要改参数文件可以通过alter system，如果重启生效的话通过卷映射去编译参数文件然后重启 docker restart xxx.

**Comment by lee1057** [comment]
想问一下opengauss 3.0的镜像是怎么下载到的？

**Comment by kamusis** [comment]
Hi

这个显示有些奇怪，我们在docker 
hub里面没有发布过3.0这个image，我们发布的是3.0.0，大小是70多MB。

enmotech/opengauss 3.0 4d3304e129df 22 months ago 1.93GB

最后面这个image感觉不是我们的发布的，22个月前本身就没有3.0版本，而且1.93GB的大小也不对。

所以想请问一下，您说的当时拉取所有仓库具体指的是做了什么操作？

**Comment by 1173710214** [comment]
感谢回复, 说来也很神奇,  我就用了下面的命令然后就下了3.0 相反是3.0.0没有下载到.
sudo docker pull --all-tags enmotech/opengauss

当时我看镜像前缀写的是enmotech, 以为只是3.0.0的缩写

**Comment by 1173710214** [comment]
> 

您好, 这个请问是先把容器内存储数据和配置的目录挂载到本地, 然后通过alter命令在 gsql里修改配置后, 重启容器即可是吗?

**Comment by kamusis** [comment]
> > 
> 
> 您好, 这个请问是先把容器内存储数据和配置的目录挂载到本地, 然后通过alter命令在 gsql里修改配置后, 重启容器即可是吗?
> 
> > gs_guc 和 gs_om命令容器里边是没有的，想要改参数文件可以通过alter system，如果重启生效的话通过编辑参数文件然后重启 docker restart xxx.

1. 有些参数是可以通过alter system生效的，不用修改参数文件
2. 有些参数必须要写入参数文件生效，可以docker exec进入容器内部，直接修改参数文件，然后重启容器即可。

**Comment by 1173710214** [comment]
明白了, 感谢二位的帮助!
