### ISSUE TITLE
docker volume  无法挂载

### ISSUE THREAD

**Issue by qanyue** [enmotech/enmotech-docker-opengauss#15]
使用环境 : arm openeuler 20 LTS root下
docker run --name opengauss --privileged=true -d -e GS_PASSWORD=Secretpassword@123 \
    -v /enmotech/opengauss:/var/lib/opengauss  -u root -p 15432:5432 \
    enmotech/opengauss:latest
无法启动
会显示
![image](https://user-images.githubusercontent.com/55617091/167140963-c60b6f46-f257-4589-aa80-ff580c7c18bf.png)

**Comment by qanyue** [comment]
ubuntu  x86 可实现，arm ubuntu 也可实现，但arm openeuler 无法实现

**Comment by lee1057** [comment]
在arm openeuler  /enmotech/opengauss 目录中的enmotech目录要保证存在。

**Comment by qanyue** [comment]
> 

![image](https://user-images.githubusercontent.com/55617091/167148617-c47a8e2c-10e0-456a-b960-1fb06c1d2fb4.png)
建立了，问题依旧

**Comment by lee1057** [comment]
755给一下

**Comment by lee1057** [comment]
我用/root可以的

**Comment by qanyue** [comment]
ok了，需要给755权限，谢谢大佬
