### ISSUE TITLE
【主从】关于Opengauss启动命令中的-M primary疑问

### ISSUE THREAD

**Issue by HuNanPengdake** [enmotech/enmotech-docker-opengauss#18]
关于一下这段命令的-M参数的疑问
```
docker run .... -M primary
```
这个-M参数我仔细查阅了 docker run --help，并未在其中找到这个参数以及解释，请问一下作者 -M primary意思是怎么样，如果我使用docker-compose方式应该如何定义它？

**Comment by kamusis** [comment]
Hi @HuNanPengdake where did you find `docker run ... -M primary` in the documentation? In deed `-M primary` should specify which openGauss database instance will run in Primary mode, on opposite to to Standby mode. that is the database parameter, not docker parameter.
We are working on operator for Kubernetes, I'm sorry to say we have no plan to support docker-compose.

**Comment by travelliu** [comment]
```
docker run --help

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
```
COMMAND  = -M primary


https://docs.docker.com/compose/compose-file/#command

**Comment by HuNanPengdake** [comment]
3ks
