### ISSUE TITLE
能否提供含postgis插件的openguass镜像，我们迫切需要

### ISSUE THREAD

**Issue by junyan-zg** [enmotech/enmotech-docker-opengauss#19]
如题，谢谢！

**Comment by kamusis** [comment]
Sorry about that, we have no plan to let the openGauss community docker image to contain all the features in Enterprise edition, you can see, we have changed the base image to openGauss Lite edition from openGauss docker image version 3.0.  

https://hub.docker.com/r/enmotech/opengauss 

But we do have a plan to make the [MogDB](https://mogdb.io) Container Edition to get all the features, including PostGIS/Yukon plugin.

**Comment by junyan-zg** [comment]
Thanks !
