### ISSUE TITLE
3.0.0配置主从时，OG_SUBNET配置参数问题

### ISSUE THREAD

**Issue by HuNanPengdake** [enmotech/enmotech-docker-opengauss#20]
关于OG_SUBNET参数值的配置作用，以及其合理性的疑问，以下是脚本文件关于OG_SUBNET参数的使用。
```
opengauss_setup_hba_conf() {
        {
                echo
                if [ 'trust' = "$GS_HOST_AUTH_METHOD" ]; then
                        echo '# warning trust is enabled for all connections'
                fi
                echo "host all all 0.0.0.0/0 $GS_HOST_AUTH_METHOD"
                echo "host replication gaussdb 0.0.0.0/0 md5"
                if [ -n "$SERVER_MODE" ]; then
                    echo "host replication repuser $OG_SUBNET trust"
                fi
        } >> "$PGDATA/pg_hba.conf"
}
```
我需要使用该镜像搭建主从，那么实际场景是运行在两台不同的PC上，这个时候关于OG_SUBNET应该如何赋值？

从以上配置中发现这行`host replication repuser $OG_SUBNET trust`
在 hba.conf增加了一行配置，使用这个OG_SUBNET网段参数配置了一个replication用户。

那么如果我的容器是运行在不是同一网段的两台pc上，该如何配置呢？

**Comment by kamusis** [comment]
host replication repuser $OG_SUBNET trust
This line means, the database instance allows the connection of database user “**repuser**” from the IP address in **$OG_SUBNET** using “**trust**” certification method. This is the connection needed for replication. 
I think maybe you should set it to the IP subnet of your standby container?
