### ISSUE TITLE
【question】ready检查

### ISSUE THREAD

**Issue by pwli0755** [enmotech/enmotech-docker-opengauss#21]
如何检查容器已经启动完毕？
如果docker run 启动容器后，要等待多久才能连接gaussdb服务？

**Comment by kamusis** [comment]
可以通过docker logs -f 查看容器日志，当不再有新日志产生，通常就表明数据库已经init完成。可以连接数据库了。

**Comment by pwli0755** [comment]
请问有什么好的“可编程”的方法吗

**Comment by kamusis** [comment]
docker logs输出日志，可以在任何编程语言里进行文本分析；或者更简单地进行循环login，一直到login成功（时间一般都在10s左右）。
如果不想要使用命令行然后分析输出，那可能需要去了解docker engine api。 https://docs.docker.com/engine/api/
