### ISSUE TITLE
Need to support 3.1.1 ! 

### ISSUE THREAD

**Issue by FinleyGe** [enmotech/enmotech-docker-opengauss#30]
Need to support 3.1.1
需要 3.1.1 的支持
In my fork, I have done the 3.1.1 support for AMD architecture.
在我的 fork 中已经实现了 3.1.1 的 amd 架构版本.

https://github.com/FinleyGe/enmotech-docker-opengauss

I need to use it immediately so I have pushed the image to my own docker repo.
我马上就要用到这个版本，所以我直接上传到自己的仓库了 

finleyge/opengauss:3.1.1

**Comment by travelliu** [comment]
提个PR ?

**Comment by FinleyGe** [comment]
okay. #31
