### ISSUE TITLE
挂载数据库文件遇到权限问题

### ISSUE THREAD

**Issue by xx529** [enmotech/enmotech-docker-opengauss#32]
通过docker-compose启动3.1.0镜像，挂载文件到指定目录出现如下错误提示
![图像](https://user-images.githubusercontent.com/64747715/229412062-4b390e07-140f-45e6-a913-143a44091089.jpeg)

要如何解决？

备注
1. windows系统下的docker环境出现该问题，linux系统下docker没有该问题
2. 如果挂载是通过docker的容器卷方式，windows和linux都没有问题

**Comment by yabinji** [comment]
挂载到指定目录，没有权限，一般是指定目录的父目录没有权限，请确认一下权限是否所有用户可写或者属主是否是70用户
