### ISSUE TITLE
OpenGauss 5.0.3 版本镜像

### ISSUE THREAD

**Issue by oubeichen** [enmotech/enmotech-docker-opengauss#45]
一直用贵组织的镜像，最近官方发布了 5.0.3 看起来修正了一些BUG，但这边一直没有发布镜像。自己尝试用官方的镜像打包方式，操作麻烦，而且发现兼容性有一点问题（比如默认 DBCOMPATIBILITY 不为 PG 而是 A，导致创建数据库需要手动指定，不然中文字符长度计算变成原有的3倍，当然不知道是不是因为升级了 5.0.3 才有的问题）。
不知道这边是否有发布计划，谢谢。

**Comment by oubeichen** [comment]
@yabinji @kamusis

**Comment by yabinji** [comment]
我们今天发布一下5.0.3

**Comment by oubeichen** [comment]
> 我们今天发布一下5.0.3

感谢，另外问一下是有配置默认 新建的所有数据库，DBCOMPATIBILITY 为 PG 吗，和官方的默认配置不一样是吗？

还有就是 lite 版本有没有发布的计划，也想在本机测试。

**Comment by yabinji** [comment]
Lite版本5.0.3版本已发布

**Comment by yabinji** [comment]
> > 我们今天发布一下5.0.3
> 
> 感谢，另外问一下是有配置默认 新建的所有数据库，DBCOMPATIBILITY 为 PG 吗，和官方的默认配置 DBCOMPATIBILITY = A 不一样是吗？
> 
> 还有就是 lite 版本有没有发布的计划，也想在本机测试。

默认DBCOMPATIBILITY 为 PG ，可以通过环境变量DBCOMPATIBILITY自定义
