### ISSUE TITLE
未指定 GS_USERNAME 时容器报错 ERROR:  role "gaussdb" already exists

### ISSUE THREAD

**Issue by oubeichen** [enmotech/enmotech-docker-opengauss#46]
如题，entrypoint.sh 的逻辑似乎有点问题，如果未指定 GS_USERNAME 会导致 gaussdb 用户被创建两次，然后报错。导致无法执行之后的 docker_process_init_files 等方法。

```shell
[2024-09-03 11:31:34.423][175][][gs_ctl]: server started (/var/lib/opengauss/data)
GS_DB = omm
Execute SQL: gsql -v ON_ERROR_STOP=1 --username omm --password testpassword@123 --dbname postgres --set db=omm --set passwd=testpassword@123
CREATE DATABASE
NOTICE:  The encrypted password contains MD5 ciphertext, which is not secure.
CREATE ROLE
ALTER ROLE

Execute SQL: gsql -v ON_ERROR_STOP=1 --username omm --password testpassword@123 --dbname postgres --set db=omm --set passwd=testpassword@123 --set user=gaussdb
ERROR:  role "gaussdb" already exists
```

**Comment by travelliu** [comment]
@oubeichen 不对吧。默认就是不指定。直接运行没问题啊

**Comment by oubeichen** [comment]
> @oubeichen 不对吧。默认就是不指定。直接运行没问题啊

你试过 /docker-entrypoint-initdb.d/ 里面的脚本有没有执行?

**Comment by travelliu** [comment]
@oubeichen 提供下你启动命令或者docker-compose.yaml文件

**Comment by oubeichen** [comment]
> @oubeichen 提供下你启动命令或者docker-compose.yaml文件

`
services:
  opengauss:
    image: enmotech/opengauss-lite:5.0.3
    container_name: spider-opengauss
    restart: unless-stopped
    privileged: true
    environment:
      TZ: Asia/Shanghai
      GS_USERNAME: admin
      GS_PASSWORD: ${OPENGAUSS_PWD}
    volumes:
      - ./data/opengauss:/var/lib/opengauss/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "LD_LIBRARY_PATH=/usr/local/opengauss/lib /usr/local/opengauss/bin/gsql -U gaussdb -W ${OPENGAUSS_PWD} -d postgres -c 'SELECT 1' || exit 1"]
      interval: 30s
      start_period: 30s
      start_interval: 5s
      timeout: 20s
      retries: 5
`

**Comment by travelliu** [comment]
```
docker run --name opengauss1 \
--privileged=true \
-e GS_PASSWORD=Abc2@123 \
-e TZ=Asia/Shanghai \
-e GS_USERNAME=admin \
-e GS_PASSWORD=Abc2@123 \
-v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
enmotech/opengauss:5.0.3


docker run --name opengauss \
--privileged=true \
-e GS_PASSWORD=Abc2@123 \
-e TZ=Asia/Shanghai \
-d \
-v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
enmotech/opengauss:5.0.3
```

@oubeichen  以上2个命令启动都正常

**Comment by oubeichen** [comment]
> ```
> docker run --name opengauss1 \
> --privileged=true \
> -e GS_PASSWORD=Abc2@123 \
> -e TZ=Asia/Shanghai \
> -e GS_USERNAME=admin \
> -e GS_PASSWORD=Abc2@123 \
> -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> enmotech/opengauss:5.0.3
> 
> 
> docker run --name opengauss \
> --privileged=true \
> -e GS_PASSWORD=Abc2@123 \
> -e TZ=Asia/Shanghai \
> -d \
> -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> enmotech/opengauss:5.0.3
> ```
> 
> @oubeichen 以上2个命令启动都正常

启动是正常，但是后面这种当 init.sql 有内容的时候，并不会执行里面的内容，可以简单写一个建表的操作。

**Comment by travelliu** [comment]
> > ```
> > docker run --name opengauss1 \
> > --privileged=true \
> > -e GS_PASSWORD=Abc2@123 \
> > -e TZ=Asia/Shanghai \
> > -e GS_USERNAME=admin \
> > -e GS_PASSWORD=Abc2@123 \
> > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > enmotech/opengauss:5.0.3
> > 
> > 
> > docker run --name opengauss \
> > --privileged=true \
> > -e GS_PASSWORD=Abc2@123 \
> > -e TZ=Asia/Shanghai \
> > -d \
> > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > enmotech/opengauss:5.0.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @oubeichen 以上2个命令启动都正常
> 
> 启动是正常，但是后面这种当 init.sql 有内容的时候，并不会执行里面的内容，可以简单写一个建表的操作。

我的执行了。我写了个select语句

**Comment by oubeichen** [comment]
> > > ```
> > > docker run --name opengauss1 \
> > > --privileged=true \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -e TZ=Asia/Shanghai \
> > > -e GS_USERNAME=admin \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > > enmotech/opengauss:5.0.3
> > > 
> > > 
> > > docker run --name opengauss \
> > > --privileged=true \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -e TZ=Asia/Shanghai \
> > > -d \
> > > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > > enmotech/opengauss:5.0.3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @oubeichen 以上2个命令启动都正常
> > 
> > 
> > 启动是正常，但是后面这种当 init.sql 有内容的时候，并不会执行里面的内容，可以简单写一个建表的操作。
> 
> 我的执行了。我写了个select语句

我给忘了，我现在的docker compose里面手动设定了GS_USERNAME=admin，要把这个去掉或者使用gaussdb。

**Comment by oubeichen** [comment]
> > > ```
> > > docker run --name opengauss1 \
> > > --privileged=true \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -e TZ=Asia/Shanghai \
> > > -e GS_USERNAME=admin \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > > enmotech/opengauss:5.0.3
> > > 
> > > 
> > > docker run --name opengauss \
> > > --privileged=true \
> > > -e GS_PASSWORD=Abc2@123 \
> > > -e TZ=Asia/Shanghai \
> > > -d \
> > > -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
> > > enmotech/opengauss:5.0.3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @oubeichen 以上2个命令启动都正常
> > 
> > 
> > 启动是正常，但是后面这种当 init.sql 有内容的时候，并不会执行里面的内容，可以简单写一个建表的操作。
> 
> 我的执行了。我写了个select语句



我今天回到测试机器重新测试了下，报错的情况是
GS_USERNAME=gaussdb

docker compose 自动读取了 .env 文件，我以为我没有配置 GS_USERNAME，其实还是配置了

如果没有设置，或者设置成其他的名字，就不会报错。
问题不大，如果能有修正就更好了，不好意思打扰你们了。
