### ISSUE TITLE
failed to solve with frontend dockerfile.v0，请问这个问题怎么解决

### ISSUE THREAD

**Issue by stanli124** [enmotech/enmotech-docker-opengauss#5]
![image](https://user-images.githubusercontent.com/33780087/111070646-9ec96580-850d-11eb-9cb7-5f21d510c21a.png)
请问在使用你提供的dockerfile文件构建容器时，出现图中所示错误改怎么解决

**Comment by stanli124** [comment]
我试了各种方法还是解决不了

**Comment by lee1057** [comment]
这个应该是docker 去拉取openEuler镜像的时候网络通讯问题（国内网有时候就这样），直接从这里下载然后导入openEuler镜像。https://repo.openeuler.org/openEuler-20.03-LTS/docker_img/

**Comment by stanli124** [comment]
十分感谢!
